version: '3'

services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:10.2.1
    container_name: teleport
    entrypoint: /bin/sh
    hostname: teleport.centagate.com
    command: -c "sleep 1 && /bin/dumb-init teleport start -c /etc/teleport/teleport.yaml"
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
